In [1]:
import os
import warnings
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import datetime as dt
import math

from sklearn.svm import SVR
from sklearn.preprocessing import MinMaxScaler

In [3]:
df = pd.read_csv("Month_Value_1.csv")
df = df.set_index("Period")
df.head(10)

,Revenue,Sales_quantity,Average_cost,The_average_annual_payroll_of_the_region
Period,,,,
01.01.2015,1.601007e+07,12729.0,1257.763541,30024676.0
01.02.2015,1.580759e+07,11636.0,1358.507000,30024676.0
01.03.2015,2.204715e+07,15922.0,1384.697024,30024676.0
01.04.2015,1.881458e+07,15227.0,1235.606705,30024676.0
01.05.2015,1.402148e+07,8620.0,1626.621765,30024676.0
01.06.2015,1.678393e+07,13160.0,1275.374508,30024676.0
01.07.2015,1.916189e+07,17254.0,1110.576805,30024676.0
01.08.2015,1.520498e+07,8642.0,1759.428870,30024676.0
01.09.2015,2.060394e+07,16144.0,1276.259909,30024676.0
01.10.2015,2.099287e+07,18135.0,1157.588904,30024676.0

In [5]:
train_start_dt = "01.01.2015"
test_start_dt = "01.10.2015"

train = df.copy()[(df.index >= train_start_dt) & (df.index < test_start_dt)][['Sales_quantity']]
test = df.copy()[df.index >= test_start_dt][['Sales_quantity']]

print('Training data shape: ', train.shape)
print('Test data shape: ', test.shape)

Training data shape:  (72, 1)
Test data shape:  (24, 1)

In [11]:
scaler = MinMaxScaler()
train['Sales_quantity'] = scaler.fit_transform(train)
test['Sales_quantity'] = scaler.transform(test)
train_data = train.values
test_data = test.values
timesteps=5
train_data_timesteps=np.array([[j for j in train_data[i:i+timesteps]] for i in range(0,len(train_data)-timesteps+1)])[:,:,0]
train_data_timesteps.shape
test_data_timesteps=np.array([[j for j in test_data[i:i+timesteps]] for i in range(0,len(test_data)-timesteps+1)])[:,:,0]
test_data_timesteps.shape
x_train, y_train = train_data_timesteps[:,:timesteps-1],train_data_timesteps[:,[timesteps-1]]
x_test, y_test = test_data_timesteps[:,:timesteps-1],test_data_timesteps[:,[timesteps-1]]

In [ ]:

model = SVR(kernel='rbf',gamma=0.5, C=10, epsilon = 0.05)
model.fit(x_train, y_train[:,0])
y_train_pred = model.predict(x_train).reshape(-1,1)
y_test_pred = model.predict(x_test).reshape(-1,1)

In [ ]:
plt.figure(figsize=(25,6))
plt.plot(train_timestamps, y_train, color = 'red', linewidth=2.0, alpha = 0.6)
plt.plot(train_timestamps, y_train_pred, color = 'blue', linewidth=0.8)
plt.legend(['Actual','Predicted'])
plt.xlabel('Timestamp')
plt.title("Training data prediction")
plt.show()